spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#server:
#  tomcat:
#    uri-encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbuser?characterEncoding=utf8
    username: root
    password: root
  jpa:
    show-sql: true

#  redis:
#    hostName: 10.80.95.143
#    port: 6379
#    password:
#    database: 2
#    timeout: 0
#    pool:
#      max-active: 8
#      max-wait: -1
#      max-idle: 8
#      min-idle: 0


